---
- name: Set host to IP mapping in /etc/hosts file of all the instances in the stack
  hosts: all
  tasks:
    - name: Import VPC setup file for all the hosts
      include_vars: group_vars/hostsip

    - name: Update /etc/hosts/ files for all the instances
      blockinfile:
        path: /etc/hosts
        block: |
          {{web01_ip}} web01_ip
          {{app01_ip}} app01_ip
          {{rmq01_ip}} rmq01_ip
          {{mc01_ip}} mc01_ip
          {{db01_ip}} db01_ip